[package]
name = "feint"
version = "0.0.0"
authors = ["Wyatt Baldwin"]
edition = "2021"
license-file = "LICENSE"

[dependencies]
clap = "~3.2.14"
dirs = "~4.0.0"
lazy_static = "~1.4.0"
num-bigint = "~0.4.3"
num-traits = "~0.2.15"
regex = "~1.6.0"
rustyline = "~10.0.0"
