[package]
name = "feint"
version = "0.0.0"
authors = ["Wyatt Baldwin"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
clap = "~2.33.3"
dirs = "~3.0.2"
lazy_static = "~1.4.0"
num-bigint = "~0.4.0"
num-traits = "~0.2.14"
regex = "~1.4.6"
rustyline = "~8.0.0"
builtin_object_derive = { path = "./src/types/builtins/builtin_object_derive" }
