[package]
name = "feint"
version = "0.0.0"
authors = ["Wyatt Baldwin"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
clap = "~2.33.3"
dirs = "~4.0.0"
lazy_static = "~1.4.0"
num-bigint = "~0.4.3"
num-traits = "~0.2.14"
regex = "~1.5.4"
rustyline = "~9.0.0"
