[package]
name = "feint"
version = "0.1.0"
authors = ["Wyatt Baldwin"]
edition = "2018"
license = "MIT"
license-file = "LICENSE"

[dependencies]
clap = "^2.33.3"
dirs = "*"
rand = "^0.8.3"
regex = "^1.4.6"
rustyline = "*"
