[package]
name = "feint"
version = "0.0.0"
authors = ["Wyatt Baldwin"]
edition = "2021"
license-file = "LICENSE"

[dependencies]
clap = "~4.0.29"
ctrlc = "~3.2.4"
dirs = "~4.0.0"
env_logger = "~0.10.0"
indexmap = "~1.9.2"
log = { version = "0.4.17", features = ["release_max_level_off"] }
num-bigint = "~0.4.3"
num-traits = "~0.2.15"
once_cell = "1.16.0"
regex = "~1.7.0"
rustyline = "~10.0.0"

# Profiling
#
# - uncomment config below
# - cargo install flamegraph
# - cargo flamegraph --root -- example/fib.py 30
#
# [profile.release]
# debug = true
