[package]
name = "feint"
version = "0.0.0"
authors = ["Wyatt Baldwin"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
clap = "~3.1.18"
dirs = "~4.0.0"
lazy_static = "~1.4.0"
num-bigint = "~0.4.3"
num-traits = "~0.2.15"
regex = "~1.5.6"
rustyline = "~9.1.2"
