pub(crate) use builtin_func::BuiltinFn;
pub(crate) use builtin_types::BUILTIN_TYPES;
pub(crate) use builtins::Builtins;
pub(crate) use namespace::Namespace;
pub(crate) use object::{ObjectExt, ObjectRef};
pub(crate) use result::{Args, CallResult, Params};

mod bool;
mod builtin_func;
mod builtin_types;
mod builtins;
mod class;
mod custom;
mod float;
mod func;
mod int;
mod namespace;
mod nil;
mod object;
mod result;
mod str;
mod tuple;
mod util;
